// <auto-generated />
using LoLovenseRainbowBridge.Recording.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoLovenseRainbowBridge.Recording.Data.Migrations
{
    [DbContext(typeof(GameplayRecordingDbContext))]
    partial class GameplayRecordingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("LoLovenseRainbowBridge.Recording.Data.GameEntity", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("TEXT")
                        .HasColumnName("game_id");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("app_version");

                    b.Property<string>("ConfigSummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("config_summary_json");

                    b.Property<string>("EndedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.HasKey("GameId");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("LoLovenseRainbowBridge.Recording.Data.LovenseRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContextDiffJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("context_diff_json");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("datetime");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("game_id");

                    b.Property<long>("OffsetMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("offset_ms");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "OffsetMs", "Id")
                        .HasDatabaseName("ix_lovense_records_game_offset");

                    b.ToTable("lovense_records", (string)null);
                });

            modelBuilder.Entity("LoLovenseRainbowBridge.Recording.Data.LovenseRecordEntity", b =>
                {
                    b.HasOne("LoLovenseRainbowBridge.Recording.Data.GameEntity", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
